DROP VIEW ReleaseData;
DROP TABLE IF EXISTS EntityRelease;
DROP TABLE IF EXISTS Release;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Label;
DROP TABLE IF EXISTS EntityTag;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Entity;
